from __future__ import annotations

import traceback
from typing import List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, HttpUrl

from main import analyze_url, normalize_url


app = FastAPI(
    title="Website Intelligence Analyzer API",
    description="API wrapper for the website analyzer. It accepts URLs and returns structured page intelligence JSON.",
    version="1.0.0",
)

# API-key auth + rate limiting (see api_security.py; env: COMPINTEL_API_KEY,
# RATE_LIMIT_PER_MINUTE, HEAVY_RATE_LIMIT_PER_MINUTE). Installed BEFORE CORS
# so 401/429 responses also carry CORS headers.
from api_security import install_security
install_security(app, service_name="website-analyzer-api")

# CORS: comma-separated origins via CORS_ORIGINS env var.
# Default covers local React dev (CRA :3000, Vite :5173).
# Set CORS_ORIGINS=https://yourapp.com in production, or "*" for open access
# (credentials are automatically disabled for "*").
import os as _os
_cors_origins = [
    o.strip() for o in _os.getenv(
        "CORS_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173",
    ).split(",") if o.strip()
]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_credentials="*" not in _cors_origins,
    allow_methods=["*"],
    allow_headers=["*"],
)


class AnalyzeRequest(BaseModel):
    url: str = Field(..., description="Full website/page URL to analyze")


class BatchAnalyzeRequest(BaseModel):
    urls: List[str] = Field(..., min_length=1, max_length=20)
    continue_on_error: bool = True


@app.get("/health")
def health():
    return {
        "status": "ok",
        "service": "website-analyzer-api",
    }


@app.post("/analyze")
def analyze_page(payload: AnalyzeRequest):
    """
    Analyze one URL and return the same structured JSON generated by main.analyze_url().
    """
    try:
        normalized_url = normalize_url(payload.url)
        return analyze_url(normalized_url)
    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail={
                "success": False,
                "message": "Website analysis failed.",
                "error": str(exc),
            },
        )


@app.post("/analyze/batch")
def analyze_batch(payload: BatchAnalyzeRequest):
    """
    Analyze multiple URLs. Useful when the React app sends homepage, collection,
    product, and blog URLs together before passing results to the merger API.
    """
    results = []

    for url in payload.urls:
        try:
            normalized_url = normalize_url(url)
            results.append({
                "url": normalized_url,
                "success": True,
                "data": analyze_url(normalized_url),
            })
        except Exception as exc:
            error_item = {
                "url": url,
                "success": False,
                "error": str(exc),
            }

            if not payload.continue_on_error:
                raise HTTPException(
                    status_code=500,
                    detail={
                        "success": False,
                        "message": "Batch analysis stopped because one URL failed.",
                        "failed": error_item,
                        "results": results,
                    },
                )

            results.append(error_item)

    return {
        "success": True,
        "count": len(results),
        "results": results,
    }
